#!/usr/bin/env bash

docker run -p 4000:4000 -v "$PWD/data":"/data" -v /var/run/docker.sock:/var/run/docker.sock --env-file local.env -e BENCH_ROOT="$PWD" -it fredtingaud/bench-runner ./start-build-bench
